# Model Experiments

In [1]:
import os
print(f"Current working directory: {os.path.basename(os.getcwd())}")

# Change to root directory
os.chdir("../")
print(f"Current working directory (Changed): {os.path.basename(os.getcwd())}")

Current working directory: notebooks
Current working directory (Changed): Wine-Quality-Predictor


In [2]:
from os.path import dirname, normpath, basename

In [3]:
# Imports
from sklearn.linear_model import ElasticNet

from src.constants import CONFIGS, PARAMS
from src.exception import CustomException
from src.logger import logger
from src.utils.basic_utils import create_directories, read_yaml, save_as_joblib, load_joblib

In [4]:
configs = read_yaml(CONFIGS).model_evaluation
params = read_yaml(PARAMS).elasticnet

[2024-01-28 08:05:38 PM]:ProjectLogger INFO: basic_utils 41 - yaml file: conf\configs.yaml loaded successfully
[2024-01-28 08:05:38 PM]:ProjectLogger INFO: basic_utils 41 - yaml file: conf\params.yaml loaded successfully


In [5]:
# Input file path
train_array_path = normpath(configs.train_array_path)

# Output file path
model_path = normpath(configs.model_path)

In [6]:
import joblib

In [7]:
model = load_joblib(model_path)
model

[2024-01-28 08:05:38 PM]:ProjectLogger INFO: basic_utils 126 - object loaded from: models\trained\elsaticnet_model.joblib


ElasticNet(alpha=0.7, l1_ratio=0.8, random_state=42)

In [8]:
type(model)

sklearn.linear_model._coordinate_descent.ElasticNet

In [9]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# module setup
%matplotlib inline
pd.options.display.precision = 3
warnings.filterwarnings("ignore")

In [10]:
train_array = np.load(train_array_path)
print(f"The shape of train_array is: {train_array.shape}")

The shape of train_array is: (5197, 14)


In [11]:
X_train = train_array[:,:-1]
print(f"The shape of X_train: {X_train.shape}")
print(f"The first 3 samples: \n{X_train[:3]}")

The shape of X_train: (5197, 13)
The first 3 samples: 
[[-0.46822898 -0.59951186  0.20546655  0.4646116  -0.71280142  0.31165933
   0.34356569 -0.29614553 -0.16888369 -1.0832659   0.01376574  0.
   2.33463722]
 [ 0.85149992 -0.35284877  1.10406349 -0.70299854  1.06747    -1.4087346
  -1.84751841 -0.20307163  0.26967864  0.59857677  1.60871671  2.33463722
   0.        ]
 [ 0.38571325  2.32961232 -2.14471006 -0.70299854  0.2347624   0.02492701
  -1.29529396 -0.32606213  1.20945505  0.26220824  1.10504798  2.33463722
   0.        ]]


In [12]:
y_train = train_array[:,-1]
print(f"The shape of y_train: {y_train.shape}")
print(f"The first 3 samples: \n{y_train[:3]}")

The shape of y_train: (5197,)
The first 3 samples: 
[5. 7. 6.]


In [13]:
X_train[:5], y_train[:5]

(array([[-0.46822898, -0.59951186,  0.20546655,  0.4646116 , -0.71280142,
          0.31165933,  0.34356569, -0.29614553, -0.16888369, -1.0832659 ,
          0.01376574,  0.        ,  2.33463722],
        [ 0.85149992, -0.35284877,  1.10406349, -0.70299854,  1.06747   ,
         -1.4087346 , -1.84751841, -0.20307163,  0.26967864,  0.59857677,
          1.60871671,  2.33463722,  0.        ],
        [ 0.38571325,  2.32961232, -2.14471006, -0.70299854,  0.2347624 ,
          0.02492701, -1.29529396, -0.32606213,  1.20945505,  0.26220824,
          1.10504798,  2.33463722,  0.        ],
        [-1.55506455,  0.20214318,  0.06722087, -0.89065017, -0.79894359,
         -1.00730935, -0.61837367, -1.49280991,  0.958848  , -1.01599219,
          1.0211032 ,  0.        ,  2.33463722],
        [-0.46822898, -0.47618032,  1.65704622,  2.07007555, -0.0810922 ,
          0.08227347,  0.45044784,  1.1332036 , -0.67009777, -0.27598142,
         -0.99357172,  0.        ,  2.33463722]]),
 array([5., 7

In [14]:
# Model Parameters
random_seed = params.random_seed
hyperparams = params.hyperparameters

print(random_seed)
print(hyperparams)

42
{'alpha': 0.7, 'l1_ratio': 0.8}


In [15]:
alpha = hyperparams.alpha
l1_ratio = hyperparams.l1_ratio

print(alpha, l1_ratio)

0.7 0.8


In [16]:
from sklearn.linear_model import ElasticNet

In [17]:
en_model = ElasticNet(alpha=alpha, l1_ratio=l1_ratio, random_state=random_seed)
en_model.fit(X_train, y_train)

ElasticNet(alpha=0.7, l1_ratio=0.8, random_state=42)

In [18]:
model_name = basename(model_path).split(".")[0]
model_name

'elsaticnet_model'

## Model Evaluation

In [19]:
from src.utils.model_utils import regression_metrics

In [20]:
test_array_path = normpath(configs.test_array_path)
scores_dir = normpath(configs.scores_dir)

In [21]:
print(test_array_path)
print(scores_dir)

data\test\test_array.npy
models\scores


In [22]:
test_array = np.load(test_array_path)
print(f"The shape of test_array: {test_array.shape}")

The shape of test_array: (1300, 14)


In [23]:
X_test = test_array[:, :-1]
y_test = test_array[:,-1]

print(f"The shape of X_test: {X_test.shape}")
print(f"The shape of y_test: {y_test.shape}")

The shape of X_test: (1300, 13)
The shape of y_test: (1300,)


In [24]:
X_test[:5], y_test[:5]

(array([[-0.15770453, -1.03117227,  2.90125736,  1.52797084, -0.31080465,
         -0.37649824,  0.18324246, -0.16318282,  0.26967864, -1.01599219,
          1.44082714,  0.        ,  2.33463722],
        [ 0.38571325,  1.86711903, -0.76225323, -0.68214836,  0.60804512,
          0.08227347,  0.3079383 ,  0.30218667,  0.3323304 , -0.54507625,
         -0.48990299,  2.33463722,  0.        ],
        [-0.31296676,  0.32547472,  0.13634371,  0.40206106, -1.02865603,
          0.42635226,  0.3079383 , -0.85458891, -0.23153545, -0.61234995,
          1.27293756,  0.        ,  2.33463722],
        [-0.70112232, -0.35284877,  1.03494064,  1.19436794, -0.45437492,
          1.74532094,  1.19862289,  0.40855684, -0.60744601, -0.141434  ,
         -0.82568214,  0.        ,  2.33463722],
        [ 0.15281991,  0.07881163, -0.83137607,  1.75732283, -0.05237815,
          1.86001387,  2.01805272,  1.39248089, -0.67009777, -0.20870771,
         -1.32935087,  0.        ,  2.33463722]]),
 array([8., 5

In [25]:
y_train_preds = en_model.predict(X_train)
y_test_preds = en_model.predict(X_test)

print(f"The shape of y_train_preds: {y_train_preds.shape}")
print(f"The shape of y_test_preds: {y_test_preds.shape}")

The shape of y_train_preds: (5197,)
The shape of y_test_preds: (1300,)


In [26]:
y_train_preds[:5], y_test_preds[:5]

(array([5.81450837, 5.81450837, 5.81450837, 5.81450837, 5.81450837]),
 array([5.81450837, 5.81450837, 5.81450837, 5.81450837, 5.81450837]))

In [27]:
train_eval_metrics = regression_metrics(y_true=y_train, y_pred=y_train_preds, features_shape=X_train.shape)
test_eval_metrics = regression_metrics(y_true=y_test, y_pred=y_test_preds, features_shape=X_test.shape)

In [28]:
train_eval_metrics

{'MAE': 0.69,
 'MSE': 0.77,
 'RMSE': 0.88,
 'MPE': -2.38,
 'MAPE': 12.38,
 'R2-Score': 0.0,
 'Adjusted R2-Score': -0.0}

In [29]:
test_eval_metrics

{'MAE': 0.67,
 'MSE': 0.74,
 'RMSE': 0.86,
 'MPE': -1.97,
 'MAPE': 11.98,
 'R2-Score': -0.0,
 'Adjusted R2-Score': -0.01}

In [30]:
dict(hyperparams)

{'alpha': 0.7, 'l1_ratio': 0.8}

In [31]:
score = {
    "params": dict(hyperparams),
    "metrics": test_eval_metrics}

score

{'params': {'alpha': 0.7, 'l1_ratio': 0.8},
 'metrics': {'MAE': 0.67,
  'MSE': 0.74,
  'RMSE': 0.86,
  'MPE': -1.97,
  'MAPE': 11.98,
  'R2-Score': -0.0,
  'Adjusted R2-Score': -0.01}}

In [43]:
import json

In [49]:
score = {
        "model_name": 2,
        "params": 3,
        "metrics": 4
    }

a = 5
b = 6



None


In [51]:
def extend_dict(**kwargs):
    my_dict = {'key1': 'value1', 'key2': 'value2'}
    my_dict.update(kwargs)
    return my_dict

# Call the function with keyword arguments
new_dict = extend_dict(**{"key3": 'value3', "key4": 'value4'})
print(new_dict)



{'key1': 'value1', 'key2': 'value2', 'key3': 'value3', 'key4': 'value4'}


In [32]:
def log_scores(filepath: str, params: dict, metrics: dict, model_name: str, **kwargs):
    score = {
        "model_name": model_name,
        "params": params,
        "metrics": metrics
    }
    
    save_path = normpath(filepath)
    os.makedirs(dirname(save_path), exist_ok=True)
    try:
        with open(save_path, "a", encoding="utf-8") as f:
            score_json = json.dumps(score)
            json.dump(score_json, f, indent=4)
        logger.info("json file saved at: %s", save_path)
    except Exception as e:
        logger.error(CustomException(e))
        raise CustomException(e) from e

In [33]:

filename = lambda prefix, suffix, extension: prefix + suffix + extension if "." in extension else prefix + suffix + "." + extension

In [34]:
filename(model_name, "_scores", ".csv")

'elsaticnet_model_scores.csv'

In [68]:
en_model.coef_.tolist()

[-0.0, -0.0, 0.0, -0.0, -0.0, 0.0, -0.0, -0.0, 0.0, 0.0, 0.0, -0.0, 0.0]

In [66]:
en_model.get_params()
en_model._parameter_constraints

{'alpha': [<sklearn.utils._param_validation.Interval at 0x155b8aac730>],
 'l1_ratio': [<sklearn.utils._param_validation.Interval at 0x155b8aac790>],
 'fit_intercept': ['boolean'],
 'precompute': ['boolean', 'array-like'],
 'max_iter': [<sklearn.utils._param_validation.Interval at 0x155b8aac7f0>,
  None],
 'copy_X': ['boolean'],
 'tol': [<sklearn.utils._param_validation.Interval at 0x155b8aac850>],
 'warm_start': ['boolean'],
 'positive': ['boolean'],
 'random_state': ['random_state'],
 'selection': [<sklearn.utils._param_validation.StrOptions at 0x155b8aac8b0>]}

In [69]:
json_path = normpath("models\scores\elsaticnet_model_scores.json")
json_path

'models\\scores\\elsaticnet_model_scores.json'

In [79]:
with open(json_path, "r") as f:
    data = f.read()
    json_data = json.load(data)
    
data, type(data)

AttributeError: 'str' object has no attribute 'read'

['[',
 '{',
 '"',
 'm',
 'o',
 'd',
 'e',
 'l',
 '_',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 ' ',
 '"',
 'E',
 'l',
 'a',
 's',
 't',
 'i',
 'c',
 'N',
 'e',
 't',
 '"',
 ',',
 ' ',
 '"',
 'h',
 'y',
 'p',
 'e',
 'r',
 'p',
 'a',
 'r',
 'a',
 'm',
 'e',
 't',
 'e',
 'r',
 's',
 '"',
 ':',
 ' ',
 '{',
 '"',
 'a',
 'l',
 'p',
 'h',
 'a',
 '"',
 ':',
 ' ',
 '0',
 '.',
 '7',
 ',',
 ' ',
 '"',
 'l',
 '1',
 '_',
 'r',
 'a',
 't',
 'i',
 'o',
 '"',
 ':',
 ' ',
 '0',
 '.',
 '8',
 '}',
 ',',
 ' ',
 '"',
 't',
 'r',
 'a',
 'i',
 'n',
 '_',
 'm',
 'e',
 't',
 'r',
 'i',
 'c',
 's',
 '"',
 ':',
 ' ',
 '{',
 '"',
 'M',
 'A',
 'E',
 '"',
 ':',
 ' ',
 '0',
 '.',
 '6',
 '9',
 ',',
 ' ',
 '"',
 'M',
 'S',
 'E',
 '"',
 ':',
 ' ',
 '0',
 '.',
 '7',
 '7',
 ',',
 ' ',
 '"',
 'R',
 'M',
 'S',
 'E',
 '"',
 ':',
 ' ',
 '0',
 '.',
 '8',
 '8',
 ',',
 ' ',
 '"',
 'M',
 'P',
 'E',
 '"',
 ':',
 ' ',
 '-',
 '2',
 '.',
 '3',
 '8',
 ',',
 ' ',
 '"',
 'M',
 'A',
 'P',
 'E',
 '"',
 ':',
 ' ',
 '1',
 '2',
 '.',
 '3',
 '8'

In [15]:
from dotenv import load_dotenv


In [16]:
load_dotenv()

MLFLOW_TRACKING_URI = os.getenv("MLFLOW_TRACKING_URI")
MLFLOW_TRACKING_USERNAME = os.getenv("MLFLOW_TRACKING_USERNAME")
MLFLOW_TRACKING_PASSWORD = os.getenv("MLFLOW_TRACKING_PASSWORD")

In [19]:
y_pred = en_model.predict(X_test)
y_pred[:5]

array([5.81450837, 5.81450837, 5.81450837, 5.81450837, 5.81450837])

In [20]:
eval_metrics = regression_metrics(y_true=y_test, y_pred=y_pred, features_shape=X_test.shape)
eval_metrics

{'MAE': 0.67,
 'MSE': 0.74,
 'RMSE': 0.86,
 'MPE': -1.97,
 'MAPE': 11.98,
 'R2-Score': -0.0,
 'Adjusted R2-Score': -0.01}

In [21]:
from src.utils.common import save_as_json


save_as_json(file_path=eval_metrics_path, data=eval_metrics)

[2024-01-26 04:27:03 PM]:ProjectLogger INFO: common 65 - json file saved at: metrics\evaluation_metrics.json


In [22]:
import mlflow
import mlflow.sklearn
from urllib.parse import urlparse

In [23]:

mlflow.set_registry_uri(MLFLOW_TRACKING_URI)
tracking_url_type_store = urlparse(mlflow.get_tracking_uri()).scheme

In [24]:
tracking_url_type_store

'http'

In [25]:
mlflow.set_experiment("Quickstart")
with mlflow.start_run():
    mlflow.log_params(hyper_params)
    mlflow.log_metrics(eval_metrics)

    if tracking_url_type_store != "file":
        mlflow.sklearn.log_model(en_model, "model", registered_model_name="ElasticNetModel")
    else:
        mlflow.sklearn.log_model(en_model, "model")

Registered model 'ElasticNetModel' already exists. Creating a new version of this model...
2024/01/26 16:27:22 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: ElasticNetModel, version 2
Created version '2' of model 'ElasticNetModel'.


## Model Predictions